<?php
/**
 * @file
 * tumblelog.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tumblelog_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'notes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03c62bf3-9980-4f71-8705-3f18bc6cd102',
    'vocabulary_machine_name' => 'groupings',
  );
  $terms[] = array(
    'name' => 'Video',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1c8139c5-11c7-4a44-b928-e921ffa55e0c',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'human ecology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2322cf80-7955-48a4-b04e-a6a663b9f833',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'linux',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '38c04641-2415-4e41-8787-d47a4e2429d3',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Image',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4150b5c4-4c1d-4eb3-b370-c08e4e875b91',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'git',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46c66fcd-92f4-4ab3-8a4a-6fa882ec5b78',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'advice',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '511f5a87-5a7a-4464-b0ef-cbad0ccc21df',
    'vocabulary_machine_name' => 'groupings',
  );
  $terms[] = array(
    'name' => 'design principles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '52bff4a8-4b3a-4df4-8b6c-a2d9cd48cb56',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'civic responsibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54af08d2-e484-456f-bd6a-b48693191011',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'File',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6be0aeaf-0e53-402e-b26a-8668d4225399',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'appropriate technology',
    'description' => '<p>In knowing a particular technology well, there\'s an understanding of its\' strengths and weaknesses. &nbsp;Appropriate technology is not an ultimate determiniation of whether or not a particular technology is appropriate, but a matter of knowing the technology well in order to evaluate the context for its\' application and determine whether its\' an appropriate use of that technology.</p>',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '90b34f05-984a-4ea0-9b06-477bc18e88b7',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'language',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '955e139f-de5c-4508-95ed-cf7c89b58999',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'language perversion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac7add0c-410d-4a99-a2b0-955c80405ab1',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Text',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c1ff601a-ef75-4f83-8e08-6ee8e27b7ffd',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'internet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c948088b-b807-4cbc-ba5a-f80a63131519',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Link',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ca78c950-b09f-426c-8e34-06c4cb897190',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'geeklog',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd0c6003-5117-4422-8fed-274910c721cc',
    'vocabulary_machine_name' => 'groupings',
  );
  $terms[] = array(
    'name' => 'blog',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd5a8df44-ebca-4083-bf28-ffec4f5791dd',
    'vocabulary_machine_name' => 'groupings',
  );
  $terms[] = array(
    'name' => 'development',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd854f407-f351-4214-91ef-ddaee3cc0506',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Quote',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'dc2c380a-93a7-4fa5-8061-d7a73761fa7b',
    'vocabulary_machine_name' => 'media',
  );
  $terms[] = array(
    'name' => 'education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc8613d7-ff25-4f35-9cda-014ccdce11dd',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'remarkomments',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f4dc9d06-bc13-4e28-9c6d-f4cca427f31c',
    'vocabulary_machine_name' => 'groupings',
  );
  $terms[] = array(
    'name' => 'drupal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f60404d5-5cc3-461a-b8c4-055eba668fa7',
    'vocabulary_machine_name' => 'topics',
  );
  return $terms;
}
